### ISSUE TITLE
I have problem with compiling the Phos 

### ISSUE THREAD

**Issue by realtuple** [whypet/Phos#1]
i used `cmake .` to build a Phos

Thing that cmake show me is:
![image](https://github.com/whypet/Phos/assets/108768635/34eb8c6b-96d0-4cc4-b6df-8e42d39a5d1a)

**Comment by whypet** [comment]
Sorry for the late response. You didn't pull the submodules, type `git submodule update --remote` in a terminal inside the directory where you cloned Phos and it'll build. Also copy the Tahoma font to `Res/tahoma.ttf` in the directory where the Phosdb build resides if text doesn't display properly
